### ISSUE TITLE
AutoCoderArgs object has no field "auto_merge"

### ISSUE THREAD

**Issue by lairdleng** [allwefantasy/auto-coder#10]
When set auto_merge true in 001_add_llm.yml, then run auto-coder --file 001_add_llm.yml, the program stop with error AutoCoderArgs object has no field "auto_merge".

os: ubuntu22.04
graphic card: GeForce RTX3070

Here is the detail:
laird@DESKTOP-08I1LGR:~/workspace/auto-coder.example$ auto-coder --file ./actions/001_add_llm.yml 
/home/laird/anaconda3/lib/python3.9/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_max_length" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/laird/anaconda3/lib/python3.9/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_max_input_length" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/laird/anaconda3/lib/python3.9/site-packages/langchain/__init__.py:29: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain_core.prompts.PromptTemplate instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/laird/anaconda3/bin/auto-coder", line 8, in <module>
    sys.exit(main())
  File "/home/laird/anaconda3/lib/python3.9/site-packages/autocoder/auto_coder.py", line 110, in main
    setattr(args, key, value)
  File "/home/laird/anaconda3/lib/python3.9/site-packages/pydantic/main.py", line 820, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "AutoCoderArgs" object has no field "auto_merge".

Can you help me find out the reason.

**Comment by allwefantasy** [comment]
Can you try to update the package with the following command:

```bash
pip install -U auto-coder  
```
and try again?
