### ISSUE TITLE
When use command /coding or /ask,  report `UDFWorker is not ready`

### ISSUE THREAD

**Issue by WayneCui** [allwefantasy/auto-coder#47]
Apple M2 ,Mac OS 13.6.7
Python 3.12.4
```
2024-10-21 17:32:10.952 | WARNING  | autocoder.auto_coder:main:261 - Detecting error when connecting to ray cluster: 'Namespace' object has no attribute 'doc_command', try to connect to ray cluster without storage support.
2024-10-21 17:32:10,997 INFO worker.py:1601 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379...
2024-10-21 17:32:11,004 INFO worker.py:1777 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265 
An error occurred: RayTaskError - ray::UDFWorker.async_apply() (pid=67444, ip=127.0.0.1, actor_id=ba7d987ab8c6cf269716180102000000, repr=<pyjava.udf.udf_worker.UDFWorker object at 0x12300fdf0>)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/wayne/Library/Python/3.9/lib/python/site-packages/pyjava/udf/udf_worker.py", line 62, in async_apply
    raise Exception(f"[{udf_name}] UDFWorker is not ready")
Exception: [deepseek_chat] UDFWorker is not ready

```

**Comment by WayneCui** [comment]
解决方案：在初始化过程中不选择模型供应商，手动使用`easy-byzerllm deploy xxx ` 部署模型

**Comment by samsomlan** [comment]
easy-byzerllm chat deepseek_chat 你好
 
╭──────────────────────────────────────────────────────────────────────────────────────── Shell Output ────────────────────────────────────────────────────────────────────────────────────────╮
│ ERROR: return fn(*args, **kwargs)                                                                                                                                                            │
│ ERROR: ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                   │
│ ERROR: File "/home/zhenlin/miniconda3/envs/auto-coder/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper                                                   │
│ ERROR: return func(*args, **kwargs)                                                                                                                                                          │
│ ERROR: ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                 │
│ ERROR: File "/home/zhenlin/miniconda3/envs/auto-coder/lib/python3.11/site-packages/ray/_private/worker.py", line 2772, in get                                                                │
│ ERROR: values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)                                                                                                        │
│ ERROR: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                      │
│ ERROR: File "/home/zhenlin/miniconda3/envs/auto-coder/lib/python3.11/site-packages/ray/_private/worker.py", line 919, in get_objects                                                         │
│ ERROR: raise value.as_instanceof_cause()                                                                                                                                                     │
│ ERROR: ray.exceptions.RayTaskError: ray::UDFWorker.async_apply() (pid=25007, ip=15.50.179.22, actor_id=c248d2ca02a2fa84098bed0847000000, repr=<pyjava.udf.udf_worker.UDFWorker       │
│ object at 0x713d20d704d0>)                                                                                                                                                                   │
│ ERROR: File "/home/zhenlin/miniconda3/envs/auto-coder/lib/python3.11/concurrent/futures/_base.py", line 449, in result                                                                       │
│ ERROR: return self.__get_result()                                                                                                                                                            │
│ ERROR: ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                   │
│ ERROR: File "/home/zhenlin/miniconda3/envs/auto-coder/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result                                                                 │
│ ERROR: raise self._exception                                                                                                                                                                 │
│ ERROR: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                 │
│ ERROR: File "/home/zhenlin/miniconda3/envs/auto-coder/lib/python3.11/site-packages/pyjava/udf/udf_worker.py", line 62, in async_apply                                                        │
│ ERROR: raise Exception(f"[{udf_name}] UDFWorker is not ready")                                                                                                                               │
│ ERROR: Exception: [deepseek_chat] UDFWorker is not ready                                                                                                                                     │
╰───────────────────────────────────────────────────────────
